name: Test scoring_api
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Setup all dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pylint
      - name: Run test
        run: |
          python -m unittest discover -s tests/unit
          python -m unittest discover -s tests/integration
      - name: Analysing the code with pylint
        run: |
          pylint --disable=broad-exception-caught,missing-function-docstring,missing-class-docstring,missing-module-docstring,deprecated-module,unused-argument,invalid-name,logging-fstring-interpolation,useless-return api.py
